language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
jdk:
  - openjdk8
  - openjdk11

env:
  - GRADLE_VERSION=5.2.1
  - GRADLE_VERSION=5.3.1
  - GRADLE_VERSION=5.4.1
  - GRADLE_VERSION=5.5.1
  - GRADLE_VERSION=5.6.4
  - GRADLE_VERSION=6.0.1
  - GRADLE_VERSION=6.1.1
  - GRADLE_VERSION=6.2.2
  - GRADLE_VERSION=6.3

install: true
script: ./gradlew --scan build -Ptest.gradle-version=$GRADLE_VERSION

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/
